### ISSUE TITLE
StringFilter strips some emoji out of the passed string

### ISSUE THREAD

**Issue by jmfryan** [cypriss/mutations#136]
When `allow_control_characters` is false (the default) StringFilter replaces characters that ruby classes as unprintable with a space. Unfortunately ruby considers some emoji as unprintable, for example 🤩. This means that those emoji are silently stripped out of the passed string by default.

This is a problem on ruby 2.4.5. Version 2.5.3 fixes the issue. I guess there's a decision here about whether this behavior should depend on the ruby version or not.

**Comment by eidge** [comment]
Same issue here - fixed temporarily by ignoring control characters but this is less than ideal as we really just want to allow emojis.

**Comment by eugeneius** [comment]
The 🤩 character is part of Unicode 10.0, support for which was added in Ruby 2.5. The `[:print:]` character class only covers known characters, which means that Ruby 2.5 considers 🤩 to be printable while Ruby 2.4 doesn't. The default behaviour of the string filter currently depends on the Ruby version.

@ivovh / @eliank / @ojundt: do you have an opinion on how we should proceed here? My preference is to make the behaviour opt-in and/or switch to a hardcoded list of control characters so that it's consistent across Ruby versions.
